### ISSUE TITLE
PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ClientException'

### ISSUE THREAD

**Issue by rohit1290** [kunalvarma05/dropbox-php-sdk#74]
I am getting the following error when I try to upload a file using the upload() method.
```
PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `POST https://content.dropboxapi.com/2/files/upload_session/finish` resulted in a `400 Bad Request` response:
Error in call to API function "files/upload_session/finish": HTTP header "Dropbox-API-Arg": commit.path: '{}' expected t (truncated...)
' in /home/user/public_html/crontab/backup2/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /home/user/public_html/crontab/backup2/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/user/public_html/crontab/backup2/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/user/public_html/crontab/backup2/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /home/user in /home/user/public_html/crontab/backup2/src/Dropbox/Http/Clients/DropboxGuzzleHttpClient.php on line 59
```

**Comment by rohit1290** [comment]
I have solved the issue, It was a mistake from my end. 
The documentation is not clear and I got confused as to where to give which file name.
Its actually `upload("path_to_ur_local_file", "file_name_to_save_at_dropbox")`
I was executing my code where the two parameters were interchanged.
