### ISSUE TITLE
Fatal error: Uncaught exception 'Kunnu\Dropbox\Exceptions\DropboxClientException'

### ISSUE THREAD

**Issue by angpulangpluma** [kunalvarma05/dropbox-php-sdk#94]
Hi! Got this error:
`Fatal error: Uncaught exception 'Kunnu\Dropbox\Exceptions\DropboxClientException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\xampp\htdocs\securingGB\vendor\kunalvarma05\dropbox-php-sdk\src\Dropbox\Http\Clients\DropboxGuzzleHttpClient.php:64 Stack trace: #0 C:\xampp\htdocs\securingGB\vendor\kunalvarma05\dropbox-php-sdk\src\Dropbox\DropboxClient.php(161): Kunnu\Dropbox\Http\Clients\DropboxGuzzleHttpClient->send('https://api.dro...', 'POST', NULL, Array, Array) #1 C:\xampp\htdocs\securingGB\vendor\kunalvarma05\dropbox-php-sdk\src\Dropbox\Dropbox.php(269): Kunnu\Dropbox\DropboxClient->sendRequest(Object(Kunnu\Dropbox\DropboxRequest), NULL) #2 C:\xampp\htdocs\securingGB\vendor\kunalvarma05\dropbox-php-sdk\src\Dropbox\Dropbox.php(239): Kunnu\Dropbox\Dropbox->sendRequest('POST', '/users/get_curr...', 'api', Array, NULL) #3 C:\xampp\htdocs\securingGB\vendor\kunalvarma05\dropbox-php-sdk\src\Dropbox\Dropbox.php(1208): Ku in C:\xampp\htdocs\securingGB\vendor\kunalvarma05\dropbox-php-sdk\src\Dropbox\Http\Clients\DropboxGuzzleHttpClient.php on line 64`

code:
```
<?php
$secret = 'secret';
$token ='token;
$id = 'DrpBxWithEncryption';

require_once 'vendor\autoload.php';

use Kunnu\Dropbox\Dropbox;
use Kunnu\Dropbox\DropboxApp;

$app = new DropboxApp($id, $secret, $token);

$dropbox = new Dropbox($app);

$account = $dropbox->getCurrentAccount();

//Id
$acntid = $account->getAccountId();

//Name
$acntnme = $account->getDisplayName();

//Email
$acntmail = $account->getEmail();

//Profile Pic URL
//$account->getProfilePhotoUrl();

//Account Type
$acnttype = $account->getAccountType();

echo $acntid . " " . $acntnme . " " . $acntmail . " " . $acnttype;
?>
```

**Comment by angpulangpluma** [comment]
Ah, to those who have experienced this problem see `https://stackoverflow.com/questions/35638497/curl-error-60-ssl-certificate-prblm-unable-to-get-local-issuer-certificate` for the solution that worked for me. Just follow the instructions in the accepted answer.
